DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'devstash_dotnet') THEN
        CREATE SCHEMA devstash_dotnet;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS devstash_dotnet.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'devstash_dotnet') THEN
        CREATE SCHEMA devstash_dotnet;
    END IF;
END $EF$;

CREATE TABLE devstash_dotnet.application_users (
    id uuid NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_application_users" PRIMARY KEY (id)
);

CREATE TABLE devstash_dotnet.identity_roles (
    id uuid NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_identity_roles" PRIMARY KEY (id)
);

CREATE TABLE devstash_dotnet.collections (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description character varying(2000),
    is_favorite boolean NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_collections PRIMARY KEY (id),
    CONSTRAINT fk_collections_users_user_id FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.identity_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_identity_user_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_identity_user_claims_application_users_user_id" FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.identity_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT "PK_identity_user_logins" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_identity_user_logins_application_users_user_id" FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.identity_user_tokens (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_identity_user_tokens" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_identity_user_tokens_application_users_user_id" FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.item_types (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    icon character varying(100),
    color character varying(32),
    is_system boolean NOT NULL,
    user_id uuid,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_item_types PRIMARY KEY (id),
    CONSTRAINT ck_item_types_owner CHECK ((is_system = TRUE AND user_id IS NULL) OR (is_system = FALSE AND user_id IS NOT NULL)),
    CONSTRAINT fk_item_types_users_user_id FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.tags (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT fk_tags_users_user_id FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.identity_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_identity_role_claims" PRIMARY KEY (id),
    CONSTRAINT "FK_identity_role_claims_identity_roles_role_id" FOREIGN KEY (role_id) REFERENCES devstash_dotnet.identity_roles (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.identity_user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT "PK_identity_user_roles" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_identity_user_roles_application_users_user_id" FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE,
    CONSTRAINT "FK_identity_user_roles_identity_roles_role_id" FOREIGN KEY (role_id) REFERENCES devstash_dotnet.identity_roles (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.items (
    id uuid NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(2000),
    content_type character varying(100) NOT NULL,
    content text,
    language character varying(100),
    url character varying(2048),
    is_favorite boolean NOT NULL,
    is_pinned boolean NOT NULL,
    last_used_at timestamp with time zone,
    user_id uuid NOT NULL,
    item_type_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_items_item_types_item_type_id FOREIGN KEY (item_type_id) REFERENCES devstash_dotnet.item_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_items_users_user_id FOREIGN KEY (user_id) REFERENCES devstash_dotnet.application_users (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.item_collections (
    item_id uuid NOT NULL,
    collection_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_item_collections PRIMARY KEY (item_id, collection_id),
    CONSTRAINT fk_item_collections_collections_collection_id FOREIGN KEY (collection_id) REFERENCES devstash_dotnet.collections (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_collections_items_item_id FOREIGN KEY (item_id) REFERENCES devstash_dotnet.items (id) ON DELETE CASCADE
);

CREATE TABLE devstash_dotnet.item_tags (
    item_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    CONSTRAINT pk_item_tags PRIMARY KEY (item_id, tag_id),
    CONSTRAINT fk_item_tags_items_item_id FOREIGN KEY (item_id) REFERENCES devstash_dotnet.items (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_tags_tags_tag_id FOREIGN KEY (tag_id) REFERENCES devstash_dotnet.tags (id) ON DELETE CASCADE
);

INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000001', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'code', TRUE, 'Snippet', 'snippet', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000002', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'sparkles', TRUE, 'Prompt', 'prompt', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000003', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'note', TRUE, 'Note', 'note', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000004', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'terminal', TRUE, 'Command', 'command', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000005', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'file', TRUE, 'File', 'file', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000006', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'image', TRUE, 'Image', 'image', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);
INSERT INTO devstash_dotnet.item_types (id, color, created_at, icon, is_system, name, slug, updated_at, user_id)
VALUES ('d0000000-0000-0000-0000-000000000007', NULL, TIMESTAMPTZ '2026-08-19T00:00:00+00:00', 'link', TRUE, 'Link', 'link', TIMESTAMPTZ '2026-08-19T00:00:00+00:00', NULL);

CREATE INDEX ix_application_users_normalized_email ON devstash_dotnet.application_users (normalized_email);

CREATE UNIQUE INDEX ux_application_users_normalized_user_name ON devstash_dotnet.application_users (normalized_user_name);

CREATE INDEX ix_collections_user_updated_at ON devstash_dotnet.collections (user_id, updated_at);

CREATE UNIQUE INDEX ux_collections_user_slug ON devstash_dotnet.collections (user_id, slug);

CREATE INDEX "IX_identity_role_claims_role_id" ON devstash_dotnet.identity_role_claims (role_id);

CREATE UNIQUE INDEX ux_identity_roles_normalized_name ON devstash_dotnet.identity_roles (normalized_name);

CREATE INDEX "IX_identity_user_claims_user_id" ON devstash_dotnet.identity_user_claims (user_id);

CREATE INDEX "IX_identity_user_logins_user_id" ON devstash_dotnet.identity_user_logins (user_id);

CREATE INDEX "IX_identity_user_roles_role_id" ON devstash_dotnet.identity_user_roles (role_id);

CREATE INDEX ix_item_collections_collection_id ON devstash_dotnet.item_collections (collection_id);

CREATE INDEX ix_item_tags_tag_id ON devstash_dotnet.item_tags (tag_id);

CREATE INDEX ix_item_types_user_updated_at ON devstash_dotnet.item_types (user_id, updated_at);

CREATE UNIQUE INDEX ux_item_types_system_slug ON devstash_dotnet.item_types (slug) WHERE "is_system" = TRUE;

CREATE UNIQUE INDEX ux_item_types_user_slug ON devstash_dotnet.item_types (user_id, slug) WHERE "user_id" IS NOT NULL;

CREATE INDEX ix_items_item_type_id ON devstash_dotnet.items (item_type_id);

CREATE INDEX ix_items_user_updated_at ON devstash_dotnet.items (user_id, updated_at);

CREATE INDEX ix_tags_user_updated_at ON devstash_dotnet.tags (user_id, updated_at);

CREATE UNIQUE INDEX ux_tags_user_slug ON devstash_dotnet.tags (user_id, slug);

INSERT INTO devstash_dotnet.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260819084836_InitialDatabaseFoundation', '10.0.11');

COMMIT;
